version: '3.3'

services:
  db:
    container_name: postgres
    image: gapp/db
    build: ./postgres
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  api:
    container_name: gapp-backend
    image: gapp/backend-dev
    depends_on:
      - db
    environment:
      NODE_ENV: development
    volumes:
      - ./src:/gapp/src
    ports:
      - 3000:3000
      - 9229:9229

volumes:
  dbdata:
    external: true
