version: '3.3'

services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432

  api:
    container_name: gapp-backend
    image: gapp/backend
    ports:
      - 3009:3000
