version: '3.3'

services:
  db:
    container_name: postgres
    image: gapp/db
    build: ./postgres
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  api:
    container_name: gapp-backend
    image: gapp/backend-migrate
    depends_on:
      - db
    environment:
      NODE_ENV: migration
      HOLD_ON_FOR_DB_HOST: ${HOLD_ON_FOR_DB_HOST:-db}
      HOLD_ON_FOR_DB_USER: ${HOLD_ON_FOR_DB_USER:-postgres}
      DB_CONNECTION_STRING: postgres://postgres:postgres@db:5432/gapp
    ports:
      - 3000:3000

volumes:
  dbdata:
    external: true
