version: '3.3'

services:
  db:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-gapp}
    ports:
      - 5432:5432

  api:
    container_name: gapp-backend
    image: gapp/backend
    depends_on:
      - db
    command: ['hold_on_for_db', 'then', 'yarn', 'migrate:run']
    environment:
      HOLD_ON_FOR_DB_HOST: ${HOLD_ON_FOR_DB_HOST:-db}
      HOLD_ON_FOR_DB_USER: ${HOLD_ON_FOR_DB_USER:-postgres}
      DB_CONNECTION_STRING: postgres://postgres:postgres@db:5432/gapp
    ports:
      - 3000:3000
