version: '3.3'

services:
  db:
    container_name: postgres
    build:
      context: ./postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-gapp}
    volumes:
      - ./db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  api:
    container_name: gapp-backend
    image: gapp/backend-dev
    depends_on:
      - db
    volumes:
      - ./src:/gapp/src
    ports:
      - 3000:3000
      - 9229:9229
