version: '3.3'

services:
  db:
    container_name: postgres
    image: gapp/db
    build: ./postgres
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  api:
    container_name: gapp-backend
    image: gapp/backend
    build: .
    depends_on:
      - db
    environment:
      NODE_ENV: test
      HOLD_ON_FOR_DB_HOST: ${HOLD_ON_FOR_DB_HOST:-db}
      HOLD_ON_FOR_DB_USER: ${HOLD_ON_FOR_DB_USER:-mocha}
      DB_CONNECTION_STRING_TEST: postgres://mocha:mocha@db:5432/mocha
    ports:
      - 3000:3000
      - 9229:9229
    command: sh -c "scripts/hold_on_for_db then yarn migrate && yarn test"

volumes:
  dbdata:
    external: true
